### PR TITLE
Logical error solved

### PR DESCRIPTION
**Pull request by shivhek25**

### CODE REVIEW

**Comment by Eunoia1729** [comment]
> Issue Number #16
> 
> # Details
> * Line number : 37
> * Explanation : Removed line asking for input.txt file

It is mentioned in code that "input.txt" and "output.txt" suitably exists. Thus, there is no scope for error there. Search harder.

**Comment by shivhek25** [comment]
@Eunoia1729 Kindly review updated commit.

**Comment by Eunoia1729** [comment]
> @Eunoia1729 Kindly review updated commit.

@shivhek25 Is the sieve function even called? Does it have scope to throw up an error? ;) 

(P.S: Do not edit your previous comment. just comment it out as a new one. :) )

**Comment by shivhek25** [comment]
Issue Number #16

Details

Line number : 2
Explanation : Added using namespace std

@Eunoia1729

**Comment by shivhek25** [comment]
@Eunoia1729 Kindly review the updated commit.

**Comment by shivhek25** [comment]
Issue Number #32 

Details

Line number : 56
Explanation : Wrong indexing used, so fixed

@Eunoia1729 Kindly check.

**Review by Eunoia1729 — CHANGES_REQUESTED** [review]
The bug has been found correctly but extra binary files are being committed  (".DS_Store"). 
Remove the excess binary files to get this merged.

**Comment by shivhek25** [comment]
@Eunoia1729 Kindly check.

**Review by Eunoia1729 — APPROVED** [review]
You have debugged the code correctly ! kudos.

**Pull request merged**
