### PR TITLE
Runtime error solved

### PR DESCRIPTION
**Pull request by shivhek25**
Issue Number #16 

# Details

<ul>
 <li> Line number : 42 </li>
 <li> Explanation : Added line </li>
</ul>

### CODE REVIEW

**Comment by Eunoia1729** [comment]
> Issue Number #16
> 
> # Details
> * Line number : 42
> * Explanation : Added line

Try compiling the code yourself and see. Still it gives RE. Search Harder. 

The Devil is back and is in the details yet again ;) .

**Comment by shivhek25** [comment]
I don't understand, the updated code seems to work fine on any online or offline IDE that I am using. :(
Also, according to the question h can be 1, but that means that 2 stones cannot be at different heights. Could you correct the constraints for h ?
@Eunoia1729

**Comment by Eunoia1729** [comment]
@ak0005 has found the bug. Kindly wait till #35 is closed.

**Comment by Eunoia1729** [comment]
Well tried @shivhek25 ! The #35 has been merged as it solved the issue first

**Pull request closed without merging**
