### PR TITLE
Fixed issue #78

### PR DESCRIPTION
**Pull request by shivhek25**
Issue Number #74 

# Details

<ul>
 <li> Line number : 42 </li>
 <li> Explanation : Printing value to 10 decimal places as precision requested in question is 10^(-8)</li>
</ul>

### CODE REVIEW

**Comment by Eunoia1729** [comment]
> Issue Number #74
> 
> # Details
> * Line number : 42
> * Explanation : Printing value to 10 decimal places as precision requested in question is 10^(-8)

good. but still the "output error" would persist. read #74 once again. 

P.S: you are close. the devil is in the details. look harder.

**Comment by shivhek25** [comment]
@Eunoia1729 Updated commit to include first 50000 prime numbers which wouldn't fit in the earlier taken value of N as 100000

**Comment by shivhek25** [comment]
Issue Number #78 

Details

Line number : 30, 31
Explanation : The compiler is unable to find return type of ternary expression or implicit conversion is unavailable between exp2 (i++) and exp3 (break).

**Comment by Eunoia1729** [comment]
> Issue Number #78
> 
> Details
> 
> Line number : 30, 31
> Explanation : The compiler is unable to find return type of ternary expression or implicit conversion is unavailable between exp2 (i++) and exp3 (break).

Congrats. Good one. And quite fast.

I would like to add a few lines to it - "break" is a statement.  ternary operator only takes expression i.e, return type exists. Thus, "break" causes an error.

**Comment by Eunoia1729** [comment]
> Issue Number #78
> 
> Details
> 
> Line number : 30, 31
> Explanation : The compiler is unable to find return type of ternary expression or implicit conversion is unavailable between exp2 (i++) and exp3 (break).

Congrats. Good one. And quite fast.

I would like to add a few lines to it - "break" is a statement. ternary operator only takes expression i.e, return type exists. Thus, "break" causes an error.

**Pull request merged**
