### PR TITLE
Fixed issue #1

### PR DESCRIPTION
**Pull request by shivhek25**
Issue Number #1 

# Details

<ul>
 <li> 42 </li>
 <li> Declared variable u2 and initialised array pre to 0 to avoid garbage value at 0th position </li>
</ul>

### CODE REVIEW

**Review by Eunoia1729 — CHANGES_REQUESTED** [review]
Considerable amount of bugs have been removed but still there are declaration and initialization bugs.
This will be merged once all the bugs of the given type are removed.
Happy debugging 👍

**Comment by shivhek25** [comment]
@Eunoia1729 Yes, but debugging them requires modifying another line in the code. Is that allowed ? Because its mentioned in the README file that multiple lines cannot be modified.

**Comment by Eunoia1729** [comment]
> @Eunoia1729 Yes, but debugging them requires modifying another line in the code. Is that allowed ? Because its mentioned in the README file that multiple lines cannot be modified.

Nope, not more than one line change is required to remove the bugs.

**Comment by shivhek25** [comment]
In the original code, variable u2 hasn’t been declared so does that come under the issue you’ve opened ? Because if not, I’ll simply use namespace std to declare all standard input output statements, and that should solve most other bugs.

**Comment by Eunoia1729** [comment]
> In the original code, variable u2 hasn’t been declared so does that come under the issue you’ve opened ? Because if not, I’ll simply use namespace std to declare all standard input output statements, and that should solve most other bugs.

"Using namespace std" dosent come under the type of error we opened an issue for. Further, in addition to my above comments, A single line may contain one or more errors. And the marking is binary. That implies, you need to identify all errors so as to get 20 pts.

Go ahead and show our mistakes!!

**Comment by shivhek25** [comment]
@Eunoia1729 None of the other errors that I have identified and isolated fall under "declaration and initialisation errors" if its neither the "using namespace std" error nor the missing semicolon at the end of typedef. I can list the other errors if you want.
Variable u2 had not been declared and the array pre had not been initialised, and both of them had been debugged in my first commit.

**Comment by Eunoia1729** [comment]
> @Eunoia1729 None of the other errors that I have identified and isolated fall under "declaration and initialisation errors" if its neither the "using namespace std" error nor the missing semicolon at the end of typedef. I can list the other errors if you want.
> Variable u2 had not been declared and the array pre had not been initialised, and both of them had been debugged in my first commit.

The devil is in the details. Look harder. ;)

**Comment by shivhek25** [comment]
@Eunoia1729 Kindly check.

**Comment by shivhek25** [comment]
@Eunoia1729 Is this PR to be closed now ?

**Pull request closed without merging**
